name: CI
on:
  - push

env:
  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
  SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
  SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      # - name: Get Playwright version
      #   id: playwright-version
      #   run: |
      #     echo "PLAYWRIGHT_VERSION=$(node -e "process.stdout.write(require('@playwright/test/package.json').version)")" >> $GITHUB_OUTPUT
      # - uses: actions/cache@v3
      #   name: Setup Playwright browser cache
      #   id: playwright-cache
      #   with:
      #     path: ~/.cache/ms-playwright
      #     key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}
      - name: Install Playwright Browsers
        run: pnpm dlx playwright install --with-deps
        # if: steps.playwright-cache.outputs.cache-hit != 'true'

        # if: steps.playwright-cache.outputs.cache-hit != 'true'

      # - uses: actions/cache@v3
      #   name: Setup NextJs build cache
      #   with:
      #     path: |
      #       ${{ steps.pnpm-cache.outputs.STORE_PATH }}
      #       ${{ github.workspace }}/.next/cache
      #     key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
      #     # If source files changed but packages didn't, rebuild from a prior cache.
      #     restore-keys: |
      #       ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      # - name: Run build
      #   run: pnpm build
      # - name: Run Playwright tests
      #   run: pnpm exec playwright test

      - name: Run Turbo CI
        run: pnpm run ci
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: tests/shop-test/playwright-report/
          retention-days: 30

      - name: run Lighthouse CI
        run: pnpm --filter shop lighthouse
